version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: revhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revhubteam4
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: revhub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./revHubBack
    container_name: revhub-backend
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "8090:8080"
    depends_on:
      - mysql
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./RevHub
    container_name: revhub-frontend
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data: